### ISSUE TITLE
筆者紹介

### ISSUE THREAD

**Issue by wamisnet** [Nefry-Community/IdeasBook#22]
筆者紹介のページで記載するものを教えてください。
自分のサイト等あればリンク等の記載もありだと思います！
例：
Nefryのハードウエア＆ソフトウエアの開発者です。
個人の活動で始めたNefryという存在がここまで大きくなって感謝の気持ちでいっぱいです！
皆さんこれからもよろしくお願いします。

チュートリアル本の例

![2018-04-17_12h55_27](https://user-images.githubusercontent.com/11423767/38847855-b96caede-423e-11e8-880b-170e94c6fa66.png)

**Comment by pokiiio** [comment]
チュートリアル本と同じで大丈夫です！
よろしくお願いします！

**Comment by 1ft-seabass** [comment]
チュートリアルと同じでお願いします！

====  1ft-seabass / @1ft-seabass

普段はフリーランスのWebフロントエンジニア。インターフェースを作りやすいNefry BTを使ってIoTやMixed Realityへの接続を日々試みている。ウォンバットが好き。

**Comment by 1ft-seabass** [comment]
うっかり自分の名前書き忘れてましたので追加しています。↑

**Comment by magicpocket** [comment]
福井眞吾 @SilkAndTikit
プログラミング言語の研究やJava API国際標準化などにたずさわってきたソフトウェアエンジニア。週休３日のセミリタイア生活に入ったのきっかけにIoTの世界に足を踏み入れ中。

**Comment by magicpocket** [comment]
@SilkAndTikit   SとAとTは大文字

**Comment by minwinmin** [comment]
たくろーどん @takudooon 
高専を卒業して、大学で宇宙工学をまなぶ学生。
とにかくコーヒーが好きで、カメラはPENTAXこそ哲学だと信じている。

**Comment by wamisnet** [comment]
完了！
皆さんありがとうございます！
